# Program 3: NumPy

In [1]:
from numpy import *

### Q1. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays. 

In [2]:
Array1 = array([79,52,41,96,87,32,62,27,16])
Array2 = array([52,70,90,60,87,32,50,5,16])
print("Array1                            : ", Array1)
print("Array1                            : ", Array2)
print("Equal to comparision              : ",Array1 == Array2)
print("Greater than comparision          : ", Array1 > Array2)
print("Greater than equal to comparision : ", Array1 >= Array2)
print("Less than comparision             : ", Array1 < Array2)
print("Less than equal to comparision    : ", Array1 <= Array2)

Array1                            :  [79 52 41 96 87 32 62 27 16]
Array1                            :  [52 70 90 60 87 32 50  5 16]
Equal to comparision              :  [False False False False  True  True False False  True]
Greater than comparision          :  [ True False False  True False False  True  True False]
Greater than equal to comparision :  [ True False False  True  True  True  True  True  True]
Less than comparision             :  [False  True  True False False False False False False]
Less than equal to comparision    :  [False  True  True False  True  True False False  True]


### Q2. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
#### [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]
#### Update sixth value to 11
#### [ 0, 0, 0, 0, 0, 0, 11, 0, 0, 0,] 

In [3]:
Vector=zeros(10)
Vector[6]=11
Vector

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

### Q3. Write a NumPy program to find common values between two arrays.
#### Expected Output:
#### Array1: [ 0 10 20 40 60]
#### Array2: [10, 30, 40]
#### Common values between two arrays:
#### [10 40] 


In [4]:
Array_1=array([0,10,20,40,60])
Array_2=array([10,30,40])
intersect1d(Array_1,Array_2)

array([10, 40])

### Q4. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. 


In [5]:
setdiff1d(Array_1,Array_2)

array([ 0, 20, 60])

### Q5. Write a NumPy program to create a new shape to an array without changing its  data.
#### Reshape 3x2:
#### [[1 2]
#### [3 4]
#### [5 6]]
#### Reshape 2x3:
#### [[1 2 3]
#### [4 5 6]] 


In [6]:
Arr1=array([[1,2],[4,5],[5,5]])
Arr1.reshape(2,3)

array([[1, 2, 4],
       [5, 5, 5]])